### ISSUE TITLE
[v3] boxShadow makes the app crash (Android)

### ISSUE THREAD

**Issue by giovannilondero** [jpudysz/react-native-unistyles#455]
### Description

It seems that various forms of boxShadow are not correctly supported.
`boxShadow` examples taken from here https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture#boxshadow.

Works without Unistyles.
Not tested on iOS.

### Steps to Reproduce

1. Move on the provided repository
2. run the app (`npm i`, `npx expo run:android`)
3. try uncommenting boxShadow examples in https://github.com/giovannilondero/unistyles-boxshadow/blob/master/app/index.tsx

### Snack or Repository Link (Optional)

https://github.com/giovannilondero/unistyles-boxshadow

### Unistyles Version

3.0.0-beta.4

### React Native Version

0.76.5

### Platforms

Android

### Expo

Yes

**Comment by sethwololo** [comment]
On iOS Simulator the app keeps running, but the shadow disappears. It works if you use BoxShadowValue without defining a color. 

On Android emulator I saw a message about a string being serialized to a double (or something like that) for a second before it crashed.

**Comment by jpudysz** [comment]
Thanks for the report, I will take a look before beta.5 release. I think I was testing it on iOS. Maybe I missed something regarding Android implementation

**Comment by jpudysz** [comment]
Hmm that's weird, I checked your code example for both Android and iOS and it works ok:

`'5 5 5 0 rgba(255, 0, 0, 0.5)'`:
![Image](https://github.com/user-attachments/assets/53edd955-5504-4270-ae32-954134f27460)

```tsx
boxShadow: [
  {
    offsetX: 5,
    offsetY: 5,
    blurRadius: 5,
    spreadDistance: 0,
    color: 'rgba(255, 0, 0, 0.5)',
  },
],
```

![Image](https://github.com/user-attachments/assets/51bb2180-791b-47b7-a4d7-6c5e4c20e089)

**Comment by giovannilondero** [comment]
Tried again with the steps above, I still **can** reproduce the issue on Android. I pasted some info below, tell me if you need anything else.
However, I could **_NOT_** reproduce the issue after updating Expo, deps, Unistyles and Nitro ([branch](https://github.com/giovannilondero/unistyles-boxshadow/tree/feat/update)), I can correctly see the shadows. Maybe it doesn't make sense to waste any more time on this.

I still need to solve some issues with XCode to build on iOS 🫠


### Android (API 34, real device)

<details><summary>Logcat extract</summary>
<p>
<pre>
2025-01-20 17:17:30.931 23309-23309 ReactNativeJNI          com.giovannil.unistylesboxshadow     E  react_native_expect failure: value.hasType<std::vector<RawValue>>()
2025-01-20 17:17:30.935 23309-23309 unknown:ViewManager     com.giovannil.unistylesboxshadow     E  Error while updating prop boxShadow
                                                                                                    java.lang.ClassCastException: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableArray
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$ArrayPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:267)
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:86)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:93)
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:702)
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:123)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:837)
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:841)
                                                                                                    	at com.facebook.react.fabric.BindingImpl.reportMount(Native Method)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1282)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
2025-01-20 17:17:30.936 23309-23309 unknown:Mo...Dispatcher com.giovannil.unistylesboxshadow     E  dispatchMountItems: caught exception, displaying mount state
                                                                                                    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'boxShadow' of a view managed by: RCTView
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:101)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:93)
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:702)
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:123)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:837)
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:841)
                                                                                                    	at com.facebook.react.fabric.BindingImpl.reportMount(Native Method)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1282)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableArray
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$ArrayPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:267)
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:86)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136) 
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56) 
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:93) 
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:702) 
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:123) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:837) 
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:841) 
                                                                                                    	at com.facebook.react.fabric.BindingImpl.reportMount(Native Method) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1282) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
2025-01-20 17:17:30.936 23309-23309 unknown:Mo...Dispatcher com.giovannil.unistylesboxshadow     E  dispatchMountItems: mountItem: next mountItem triggered exception!
2025-01-20 17:17:30.937 23309-23309 unknown:Mo...Dispatcher com.giovannil.unistylesboxshadow     E  dispatchMountItems: mountItem: IntBufferBatchMountItem [surface:11]:
2025-01-20 17:17:30.937 23309-23309 unknown:Mo...Dispatcher com.giovannil.unistylesboxshadow     E  dispatchMountItems: mountItem: UPDATE PROPS [12]: <hidden>
2025-01-20 17:17:30.937 23309-23309 unknown:Su...ingManager com.giovannil.unistylesboxshadow     E  Views created for surface {11}:
2025-01-20 17:17:30.937 23309-23309 unknown:Su...ingManager com.giovannil.unistylesboxshadow     E  <DebuggingOverlay id=4 parentTag=6 isRoot=false />
2025-01-20 17:17:30.937 23309-23309 unknown:Su...ingManager com.giovannil.unistylesboxshadow     E  <RCTView id=6 parentTag=11 isRoot=false />
2025-01-20 17:17:30.937 23309-23309 unknown:Su...ingManager com.giovannil.unistylesboxshadow     E  <RNCSafeAreaProvider id=10 parentTag=11 isRoot=false />
2025-01-20 17:17:30.938 23309-23309 unknown:Su...ingManager com.giovannil.unistylesboxshadow     E  <RootView id=11 parentTag=16908290 isRoot=true />
2025-01-20 17:17:30.938 23309-23309 unknown:Su...ingManager com.giovannil.unistylesboxshadow     E  <RCTView id=12 parentTag=10 isRoot=false />
2025-01-20 17:17:30.938 23309-23309 unknown:BridgelessReact com.giovannil.unistylesboxshadow     W  ReactHost{0}.handleHostException(message = "Error while updating property 'boxShadow' of a view managed by: RCTView")
2025-01-20 17:17:30.939 23309-23309 unknown:ReactNative     com.giovannil.unistylesboxshadow     E  Exception in native call
                                                                                                    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'boxShadow' of a view managed by: RCTView
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:101)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:93)
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:702)
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:123)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:837)
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:841)
                                                                                                    	at com.facebook.react.fabric.BindingImpl.reportMount(Native Method)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1282)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableArray
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$ArrayPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:267)
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:86)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136) 
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56) 
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:93) 
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:702) 
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:123) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:837) 
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:841) 
                                                                                                    	at com.facebook.react.fabric.BindingImpl.reportMount(Native Method) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1282) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
2025-01-20 17:17:30.941 23309-23440 unknown:BridgelessReact com.giovannil.unistylesboxshadow     W  ReactHost{0}.getOrCreateDestroyTask()
2025-01-20 17:17:30.946 23309-23440 unknown:BridgelessReact com.giovannil.unistylesboxshadow     W  ReactHost{0}.raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "Error while updating property 'boxShadow' of a view managed by: RCTView")
2025-01-20 17:17:30.948 23309-23440 unknown:ReactHost       com.giovannil.unistylesboxshadow     E  Unhandled SoftException
                                                                                                    com.facebook.react.bridge.ReactNoCrashSoftException: raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "Error while updating property 'boxShadow' of a view managed by: RCTView")
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.raiseSoftException(ReactHostImpl.java:942)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.getOrCreateDestroyTask(ReactHostImpl.java:1575)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.lambda$destroy$7(ReactHostImpl.java:541)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.$r8$lambda$uso21_D6dCZdcf-JomVD56kdG4c(Unknown Source:0)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl$$ExternalSyntheticLambda37.call(D8$$SyntheticClass:0)
                                                                                                    	at com.facebook.react.runtime.internal.bolts.Task$2.run(Task.java:240)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'boxShadow' of a view managed by: RCTView
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:101)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:93)
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:702)
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:123)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:837)
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:841)
                                                                                                    	at com.facebook.react.fabric.BindingImpl.reportMount(Native Method)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1282)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableArray
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$ArrayPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:267)
                                                                                                    	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:86)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136) 
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56) 
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:93) 
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.java:702) 
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:123) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:837) 
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:841) 
                                                                                                    	at com.facebook.react.fabric.BindingImpl.reportMount(Native Method) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1282) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
<pre>
</details> 

<img src="https://github.com/user-attachments/assets/f474d7b3-fcae-4597-927a-ab5ae7c26562" width="400"/>

**Comment by jpudysz** [comment]
Crash comes from React Native itself. So whatever Unistyles passed from JS to RN View caused a crash.

If it works on `beta.5` then I would close it 💪🏼

**Comment by giovannilondero** [comment]
It's fine to me. Thank you!
